### ISSUE TITLE
[BUG] Some Players dont get new Faces.

### ISSUE THREAD

**Issue by FM2222** [Maradonna90/NewGAN-Manager#127]
**Describe the bug**
I'm in the 2027 season and I've noticed that some players don't get faces anymore. All the players who didn't get it have black skin as far as I can see. 

I have selected the "Preserve" mode and allowed duplicates. The players are in the RTF file but the face is not created. When I enter the UID in the search field after the replace, the error message Player with ID does not exist appears. 

The newgan log shows the message

Ethnicity African has no faces left for mapping. Skipping player 2002497151

![Error](https://user-images.githubusercontent.com/101413706/157901827-824986c2-d13a-453c-977a-5b780caa64fe.PNG)

[FM 2022.txt](https://github.com/Maradonna90/NewGAN-Manager/files/8233403/FM.2022.txt)

![No face for mapping](https://user-images.githubusercontent.com/101413706/157903175-f90a635a-07c2-489d-a124-08c6cde93081.PNG)

**Comment by rospaseta** [comment]
I got same issue, preserve sometimes won't give faces for newgen, even they are on .xml file. Doesn't matter what country or skin colour they got they just won't get faces. Have been tried also generate totally new face everyone, but then it lose those older ones and gives new ones face :D my save is currently 5th seasons. atm my youth has only 1 of 16 players real looks face.

**Comment by Maradonna90** [comment]
def a bug. bc the player has Caucasian ethnicity but the mapper looks in African ethnicity to find a face.

@rospaseta very unclear if your issue is related bc lack of information.

**Comment by Manningham** [comment]
@Maradonna90 It looks like there's a [fallback case](https://github.com/Maradonna90/NewGAN-Manager/blob/4512e795aec0c2b58e3133632c092bc7ceb9d62a/src/mapper.py#L83) which sets player ethnicity to "African" in situations where it shouldn't?

Ex:

```txt
| 2002855376| USA       | MEX       | Gustavo Macías                               | 2         | 11        | 7         | 
```
```txt
2022-06-05 21:20:57,539 | NewGAN App: 77108/226428: ['2002855376', 'USA', 'MEX', '7'], Caucasian, South American
2022-06-05 21:20:57,539 | NewGAN App: Ethnicity African has no faces left for mapping. Skipping player 2002855376
```

Certainly I think it's fine to have players with African ethnicity originating from Mexico. But strictly following the app logic, it looks like the evaluated ethnicity should either be "South American" or "Caucasian" to match "USA" and "MEX" nationalities as listed in `cfg.json`:
```
{
    ...
    "MEX": "South American",
    ...
    "USA": "Caucasian",
}
```

Perhaps this is an issue? I'm noticing that for every case where the "Ethnicity African has no faces left for mapping" message arises, the player's skin tone is one of the values in [the conditional block containing the fallback case linked ^](https://github.com/Maradonna90/NewGAN-Manager/blob/4512e795aec0c2b58e3133632c092bc7ceb9d62a/src/mapper.py#L75-L83).

WRT why the "Ethnicity African has no faces left for mapping" message, I guess [the image selection pool is empty in `pick_image()`](https://github.com/Maradonna90/NewGAN-Manager/blob/4512e795aec0c2b58e3133632c092bc7ceb9d62a/src/mapper.py#L129). Unclear to me on sight why that would be happening, especially because African pictures are successfully selected later on in the program execution, so the selection pool is certainly populated at those later times.

Here's my log file in case it helps, as well as the rtf: 
[newgan_rtf_and_log.zip](https://github.com/Maradonna90/NewGAN-Manager/files/8840058/newgan_rtf_and_log.zip)

As a workaround, I've added portraits for the 4 youth intake players who were missing them by adding a line for each of them to the `config.xml` file in my player pictures directory (I have it installed here: `...\Documents\Sports Interactive\Football Manager 2022\graphics\FMNEWGANv2 + Update 1\config.xml`, you may have it somewhere else). You can add a line like the following, where the `from=` bit is the file path to a player portrait relative to the .xml file, and the `{PLAYER_ID}` bit of the `to=` part is the player's ID.

<record from="Scandinavian/Scandinavian3477" to="graphics/pictures/person/{PLAYER_ID}/portrait"/>

**Comment by Maradonna90** [comment]
@Manningham thanks for the very detailed post. There is definitely an issue and I think your helped tremendously narrowing it down.

**Comment by gert-dubois** [comment]
I use the following work around to generate faces for my newgens until this issue is fixed.

1. Make a backup of your `config.xml` in your newgan graphics folder.
2.  Export all newgen players you want to generate faces for to `.rtf`, I personally limit the custom filter by age 15-16. This will also have some newgens from the previous year, but it doesn't matter
3. Use the `Generate` option in newgan and use the generated file as input, this will overwrite your previous `config.xml` in the newgan graphics folder
4. Edit the `config.xml` file with notepad and copy all `<record from="..." to="..."/> lines from the file.
5. Paste the lines underneath the last `<record .../>` in your backup `config.xml`
6. Remove the `config.xml` you generated and rename your backup to `config.xml`
7. Reload the skin data in FM

Because of how FM loads graphics data it will only use the first portrait mapping record for a player it loads. So even though you generated duplicates for previous newgens, because they are below the old picture mappings FM will skip over them. Over time this will make your config.xml file much bigger, but for me this at least provides a workaround.

**Comment by lmilne96** [comment]
@Maradonna90 I believe this is caused by [this commit](https://github.com/Maradonna90/NewGAN-Manager/commit/4530cdabdf8423b163af8ea387b549ad5977befa). Specifically, removing these lines from `mapper.py` prevents the issue from occurring:
```
30    for eth in self.eth_map:
31        self.eth_map[eth] = self.eth_map[eth] - set(prf_imgs)
```
If I'm reading correctly, this block should only run if duplicates is set to false.

**Comment by ray85b** [comment]
> @Maradonna90 I believe this is caused by [this commit](https://github.com/Maradonna90/NewGAN-Manager/commit/4530cdabdf8423b163af8ea387b549ad5977befa). Specifically, removing these lines from `mapper.py` prevents the issue from occurring:
> 
> ```
> 30    for eth in self.eth_map:
> 31        self.eth_map[eth] = self.eth_map[eth] - set(prf_imgs)
> ```
> 
> If I'm reading correctly, this block should only run if duplicates is set to false.

Just created an account to say this solved the problem for me! I have been having this issue for months with preserve function, and taking those 2 lines out got all my skipped newgens their faces

**Comment by talelburg** [comment]
> @Maradonna90 I believe this is caused by [this commit](https://github.com/Maradonna90/NewGAN-Manager/commit/4530cdabdf8423b163af8ea387b549ad5977befa). Specifically, removing these lines from `mapper.py` prevents the issue from occurring:
> 
> ```
> 30    for eth in self.eth_map:
> 31        self.eth_map[eth] = self.eth_map[eth] - set(prf_imgs)
> ```
> 
> If I'm reading correctly, this block should only run if duplicates is set to false.

For sure this has to be added? Just spent two hours figuring this up. 
Just need to make it
```
if not duplicates and mode in ....
```
This solved it instantly of course.

**Comment by talelburg** [comment]
> > @Maradonna90 I believe this is caused by [this commit](https://github.com/Maradonna90/NewGAN-Manager/commit/4530cdabdf8423b163af8ea387b549ad5977befa). Specifically, removing these lines from `mapper.py` prevents the issue from occurring:
> > ```
> > 30    for eth in self.eth_map:
> > 31        self.eth_map[eth] = self.eth_map[eth] - set(prf_imgs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I'm reading correctly, this block should only run if duplicates is set to false.
> 
> For sure this has to be added? Just spent two hours figuring this up. Just need to make it
> 
> ```
> if not duplicates and mode in ....
> ```
> 
> This solved it instantly of course.

This of course doesn't work but something very similar does.

**Comment by Maradonna90** [comment]
fixed it. Re-Open if issue persist with NewGAN-Manager versions higher than 1.3.1
