### ISSUE TITLE
The manager is not importing any faces even with the rtf file

### ISSUE THREAD

**Issue by youbears** [Maradonna90/NewGAN-Manager#137]
**Describe the bug**
When I click the generate button, the application finishes but i get no faces in game

**To Reproduce**
I follow the correct process but the faces do not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/103641647/163381829-566ca3bd-2e99-43fe-8b78-c4414f3160c6.png)
![image](https://user-images.githubusercontent.com/103641647/163381861-10060aab-01d9-46fe-be72-0d01f706a99d.png)

**Desktop (please complete the following information):**
 - OS: Windows 

**Attachments**
[2021.zip](https://github.com/Maradonna90/NewGAN-Manager/files/8488765/2021.zip)
The zip is my rtf

**Comment by KevinHaleydt** [comment]
Did you reload the skin in the preferences after replacing the faces?

**Comment by rospaseta** [comment]
I've same issue with preserve option. Did everything what Zealand told to do on guide video and guide on here, still no new faces some of newgen players. Players id's is in that RTF file but it won't generate faces to them and it won't transfer it to the config file. Only way i've managed to get face is manually do the lines on config file. Sometimes get working if i make totally new generated faces for every single newgens but lose those faces what i like and still some missing faces. I've tried also backup copy config files and copy/paste all line to the new config files after generate faces, didn't help at all. Sometimes new season all newgen get faces, except those who haven't get it in the before. Really irritating "bug"

**Comment by Maradonna90** [comment]
@rospaseta stop spamming in every issue pls.

**Comment by rospaseta** [comment]
It's not spamming if only 2 post or reply on same issue, 3 or more post/reply is spamming. and spamming with same issue on short time period is spamming, first time i mention this issue was march 26th without any respond. Over month later responding, you could answer on first post "i'm on it."(took me to write it like 4seconds)  then i wouldn't post same issue again. Then i know that you or someone else is trying to fix it. 2nd time i post, which is this, i was checking if someone on here have solution to work around it, and haven't read other bugs threat. If peoples won't report every issue on program then how to programmer can fix those issues? They just thinking "nobody report, then it's working perfectly"

**Comment by Maradonna90** [comment]
@rospaseta one bug, one issue. pretty simple.

**Comment by rospaseta** [comment]
Anyway, do you have any idea why this issue happens? when i do that RTF file on FM22, it shows those players on there, but on some reason it won't make those players to the config file and then they haven't those regen faces. Which looks like mass murderers. This happens atleast on preserve setup. Overwrite and generate lose those earlier years newgen generated faces for some odd reason and they get those ugly faces. is there some sort work around it?

**Comment by Maradonna90** [comment]
no i have no idea. might be related to some other issue

**Comment by rospaseta** [comment]
This was on newgan log 
![newganlog](https://user-images.githubusercontent.com/102409258/169313629-86ea27f3-fc05-465d-abdc-9e2a65e459e6.png)
