### ISSUE TITLE
Generating Faces not working "NewGAN App: Mapping for is missing. Skipping player"

### ISSUE THREAD

**Issue by pilyy** [Maradonna90/NewGAN-Manager#146]
Hello,

I downloaded "FMNEWGANv2 + Update 1" but generating faces does not work for me. It workded one time at the beginning for another savegame. but since i started a new game it didnt work yet. It always shows: NewGAN App: Mapping for  is missing. Skipping player in the newgan.log.

What do I do wrong?

**Comment by pilyy** [comment]
[Generating_Faces_not_working_ NewGAN_App _Mapping_for__is_missing._Skipping_player .zip](https://github.com/Maradonna90/NewGAN-Manager/files/9452191/Generating_Faces_not_working_.NewGAN_App._Mapping_for__is_missing._Skipping_player.zip)

Here are the 
-config.xml
-newgan.log
-rtf File

**Comment by pilyy** [comment]
Misclicked as closed

**Comment by Nullsubstance** [comment]
I do have the same issue and can't find solution, did you have any luck?

**Comment by Nullsubstance** [comment]
Ok after looking around i finally found solution. Problem is in the RTF file I export from FM.

1. I read Maradonna90 recommend to export with English UK as language in-game, i had another language, dont know if this is a problem or not, since i had another issue.
2. After checking the file i notice nationality where blank in notepath, after comparing my game with tutorial video i notice i have a flag skin that covers the 3words that describe nation of player. after taking off this add-on and export again i got nationality in the file again and work like a charm.

I check your RTF file and you have the same issue, black nation.

CYA

**Comment by benwangyan** [comment]
> 

how do you take off the add on. i cleared my graphics folder but the 3words still covered. I tried the default skin too. Thx
