### ISSUE TITLE
[BUG] Not generating faces for certain nationalities

### ISSUE THREAD

**Issue by B1gum** [Maradonna90/NewGAN-Manager#156]
**Describe the bug**
When trying to add faces for the newgens, some nationalities are excluded, for instance it doesn't generate faces for Danish and Swedish newgens, whilst the Icelandic ones get correct faces. See this imgur: https://imgur.com/gallery/WUdykFU, where a Danish player, who shows up in the .rtf file does not get a new face. This happens for all Danish and Swedish players.

**To Reproduce**
1. Create .rtf file as you would normally, including all players (that means Danish and Swedish players are included9
2. Go to newgan and hit either create, preserve or replace
3. Reload skin

**Expected behavior**
I would expect that Danish and Swedish players get new faces to, but that doesn't seem to happen.

**Screenshots**
https://imgur.com/gallery/WUdykFU

**Desktop (please complete the following information):**
 - OS:
MacOS Monterey, v. 12.6

**Attachments**
Add your `newgan.log` and RTF-File

[RTF-file.pdf](https://github.com/Maradonna90/NewGAN-Manager/files/10338597/RTF-file.pdf)
[config.pdf](https://github.com/Maradonna90/NewGAN-Manager/files/10338652/config.pdf)

There is no .log file in the folder, so i cannot add that.

**Comment by Ayal1** [comment]
The issue you're facing is because your Football Manager's game/data language setting in preferences isn't set to English so the 3 letter codes on the view that's exported doesn't match what the program expects. If you temporarily set your game's language to English, do all the process of getting the .RTF file with the view and see that instead of `DAN` you have `DEN` for Denmark then it should work. 
The reason it worked (or sort of worked for some newgens) is that the Danish 3 letter country codes *happens* to have the same or country codes for some countries, so it could trick you into thinking something else is wrong.

**Comment by B1gum** [comment]
Thank you so much
