### ISSUE TITLE
Newgan manager crash every time opens, used to work fine [BUG]

### ISSUE THREAD

**Issue by fcsteamacc** [Maradonna90/NewGAN-Manager#235]
When opening the application, it will crash instantly on launch with Traceback error.

![image](https://github.com/Maradonna90/NewGAN-Manager/assets/166551088/530e0699-23b0-4ccc-a24b-0f70c59f7c7b)

Windows

Edit: I must say that this only started occurring after the most recent content update.

**Comment by Fak1ndAngel** [comment]
I have the same problem, if anyone can help us I would greatly appreciate it!!

@Maradonna90

**Comment by Pinball7wiz** [comment]
Hi, I've also had this issue since yesterday.  Clearing out the app data and reinstalling also hasn't helped at all.  Any help would be greatly appreciated! <3

(Also here is the full error code line if it helps)
Traceback (most recent call last):
  File "\app\newganmanager_main_.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 663, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 285, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 258, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 113, in create
    self.interface._startup()
  File "\app_packages\toga\app.py", line 624, in startup
    self.startup()
  File "\app\newganmanager\app.py", line 62, in startup
    self.profilemanager = Profile_Manager(Config_Manager().get_latest_prf(str(self.paths.app)+"/.user/cfg.json"), str(self.paths.app))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\app\profile_manager.py", line 10, in __init
    self.prf_cfg = self.load_config(root_dir+"/.user/"+name+".json")
                                    ~~~~^~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by fcsteamacc** [comment]
> I have the same problem, if anyone can help us I would greatly appreciate it!!
> 
> @Maradonna90



> Hi, I've also had this issue since yesterday. Clearing out the app data and reinstalling also hasn't helped at all. Any help would be greatly appreciated! <3
> 
> (Also here is the full error code line if it helps) Traceback (most recent call last): File "\app\newganmanager_main_.py", line 4, in main().main_loop() File "\app_packages\toga\app.py", line 663, in main_loop self._impl.main_loop() File "\app_packages\toga_winforms\app.py", line 285, in main_loop raise self._exception File "\app_packages\toga_winforms\app.py", line 258, in run_app self.create() File "\app_packages\toga_winforms\app.py", line 113, in create self.interface._startup() File "\app_packages\toga\app.py", line 624, in startup self.startup() File "\app\newganmanager\app.py", line 62, in startup self.profilemanager = Profile_Manager(Config_Manager().get_latest_prf(str(self.paths.app)+"/.user/cfg.json"), str(self.paths.app)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "\app\profile_manager.py", line 10, in __init self.prf_cfg = self.load_config(root_dir+"/.user/"+name+".json") ~~~~^~~ TypeError: can only concatenate str (not "NoneType") to str

Hey guys.

I should've scrolled down, these issues were resolved on previous issues see below.

https://github.com/Maradonna90/NewGAN-Manager/issues/212#issuecomment-1872496593
