### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zweltim** [Maradonna90/NewGAN-Manager#239]
Only some countries gets changed and others don't. Most African regens get changed while europeans mainly didnt 

![Ekran görüntüsü 2024-05-09 041942](https://github.com/Maradonna90/NewGAN-Manager/assets/169320361/68410103-eb56-4af8-827a-bd3794f0ef5e)
![Ekran görüntüsü 2024-05-09 042136](https://github.com/Maradonna90/NewGAN-Manager/assets/169320361/3b613648-0146-4a7c-a3ef-2491b3117cfb)

Windows 11
 Cant attach rtf

**Comment by Ayal1** [comment]
This almost certainly because your game language is not set to English, therefore the 3 letter codes for the different countries would be different than the English ones. Try setting your game language to English before exporting the RTF file and trying again. After you've generated the RTF file you can change back to the previous language and you'll need to change back to English any time you want to generate the RTF file.

**Comment by zweltim** [comment]
Tried everything except changing the language. problem solved, thank you!
