### ISSUE TITLE
[BUG] NewGAN Manager stuck on "map player to"

### ISSUE THREAD

**Issue by Furny88** [Maradonna90/NewGAN-Manager#62]
**Describe the bug**
A clear 
[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/5937967/newgan.log)

[newgan.log](https://github.com/Maradonna90/NewGAN-Manager/files/5937973/newgan.log)

and concise description of what the bug is.

when i click replace players the black bar fills up a 1/4 and then nothing happens. if i click again the bar fills up again and still nothing happens.

i have followed all the steps and have the latest version v1.2.0. tried restarting and uninstalling and reinstalling from a different download and same result.

![Screenshot 2021-02-07 012329](https://user-images.githubusercontent.com/78669369/107133726-1e4a9000-68e3-11eb-8c46-9e4767774826.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Attachments**
Add your `newgan.log` and RTF-File

**Comment by pakaufmann** [comment]
I see the same bug, but on Windows. The log hints at nothing specifically.

**Comment by Maradonna90** [comment]
have you checked the troubleshooting guide: https://github.com/Maradonna90/NewGAN-Manager/wiki/Troubleshooting ?
If it doesn't help could you show the content of your image folder (https://github.com/Maradonna90/NewGAN-Manager/wiki/Troubleshooting) ?

**Comment by pakaufmann** [comment]
After debugging the Python-Code I think i found the problem: I only downloaded the "NewGAN-Manager" program but not the 9GB ZIP-File with the faces in it. So, turns out I just can't properly read the installation How-To -.-.

Maybe the program could tell this a bit clearer instead of just failing sort of silently. When the `eth_dirs` variable in `mapper.py` is empty it could end the process and tell the user something along the line of "Could not find any faces to apply. Please download the faces too, without it it won't work".

**Comment by Maradonna90** [comment]
Created a new issue with a new feature #63

**Comment by snow-fy** [comment]
I do have the same problem here, with bar only filling up 1/4 everytime I press replace faces without nothing happening. Thing is that I did download the 9 GB zip with the faces and I located them in the graphics folder like the instructions said.
